// <auto-generated />
namespace MasterGradeSearch.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Institute_Description_Images_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Institute_Description_Images_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "201506181624358_Institute_Description_Images_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
